import os
import pandas as pd
from fpdf import FPDF
from datetime import datetime

# Constantes de configuração
SUPPORTED_EXTENSIONS = ('.xls', '.xlsx', '.xlsm', '.ods', '.odf')
MAX_COLUMN_WIDTH = 200
BASE_CHAR_WIDTH_MM = 2.5
CELL_MARGIN_MM = 4
FONT_ARIAL_REGULAR = "C:\\Windows\\Fonts\\arial.ttf"
FONT_ARIAL_BOLD = "C:\\Windows\\Fonts\\arialbd.ttf"

def get_current_time():
    """
    Returns the current time formatted as HH:MM:SS.
    
    Returns:
        str: The current time string.
    """
    return datetime.now().strftime("%H:%M:%S")

def print_log(emoji, category, function_name, message):
    """
    Prints a formatted log message following the required pattern.
    
    Args:
        emoji (str): The emoji indicator (e.g., ℹ️, 🔹, ✅, 🔴).
        category (str): The category of the log (e.g., LOG, STEP, SUCCESS, ERROR).
        function_name (str): The name of the function or step.
        message (str): The message to log.
    """
    print(f"[{get_current_time()}] {emoji} [{category}] [{function_name}] {message}")

def get_col_widths(df):
    """
    Calculates the required width for each column in a DataFrame based on content.
    
    Args:
        df (pd.DataFrame): The DataFrame to analyze.
        
    Returns:
        list: A list of column widths in mm.
    """
    print_log("🔹", "STEP", "get_col_widths", f"Starting with df of shape {df.shape}")
    widths = []
    try:
        for col in df.columns:
            max_len = len(str(col))
            if not df[col].empty:
                col_max_len = df[col].apply(lambda x: len(str(x))).max()
                max_len = max(max_len, col_max_len)
            widths.append(max_len * BASE_CHAR_WIDTH_MM + CELL_MARGIN_MM)
        print_log("✅", "SUCCESS", "get_col_widths", "Completed calculating widths")
        return widths
    except Exception as e:
        print_log("🔴", "ERROR", "get_col_widths", f"Failed to calculate column widths: {e}. Fix by checking DataFrame content types.")
        raise

def get_excel_files(folder_path):
    """
    Gets a list of all supported Excel files in the given folder.
    
    Args:
        folder_path (str): The path to search for files.
        
    Returns:
        list: A list of file names that match supported extensions.
    """
    print_log("🔹", "STEP", "get_excel_files", f"Starting search in {folder_path}")
    try:
        files = [f for f in os.listdir(folder_path) if f.lower().endswith(SUPPORTED_EXTENSIONS)]
        print_log("✅", "SUCCESS", "get_excel_files", f"Completed finding {len(files)} files")
        return files
    except Exception as e:
        print_log("🔴", "ERROR", "get_excel_files", f"Failed to list files: {e}. Fix by checking directory permissions or path validity.")
        raise

def setup_fonts(pdf):
    """
    Configures fonts for the PDF generation, preferring Arial if available.
    
    Args:
        pdf (FPDF): The FPDF instance to configure.
        
    Returns:
        str: The name of the font family selected.
    """
    print_log("🔹", "STEP", "setup_fonts", "Starting font configuration")
    try:
        if os.path.exists(FONT_ARIAL_REGULAR):
            pdf.add_font("Arial", "", FONT_ARIAL_REGULAR)
            if os.path.exists(FONT_ARIAL_BOLD):
                pdf.add_font("Arial", "B", FONT_ARIAL_BOLD)
            print_log("✅", "SUCCESS", "setup_fonts", "Completed font configuration using Arial")
            return "Arial"
        print_log("✅", "SUCCESS", "setup_fonts", "Completed font configuration using helvetica fallback")
        return "helvetica"
    except Exception as e:
        print_log("🔴", "ERROR", "setup_fonts", f"Failed to setup fonts: {e}. Fix by checking font file paths or FPDF font cache.")
        raise

def clean_column_names(df):
    """
    Removes 'Unnamed' column headers generated by pandas for empty headers.
    
    Args:
        df (pd.DataFrame): The DataFrame to clean.
    """
    print_log("🔹", "STEP", "clean_column_names", "Starting to clean column names")
    try:
        df.columns = [col if not str(col).startswith('Unnamed') else '' for col in df.columns]
        print_log("✅", "SUCCESS", "clean_column_names", "Completed cleaning column names")
    except Exception as e:
        print_log("🔴", "ERROR", "clean_column_names", f"Failed to clean column names: {e}. Fix by validating DataFrame columns.")
        raise

def calculate_sheet_dimensions(df, col_widths):
    """
    Calculates the total width and height required for the PDF page.
    
    Args:
        df (pd.DataFrame): The DataFrame to be written.
        col_widths (list): The list of column widths.
        
    Returns:
        tuple: (total_width, total_height) for the PDF page.
    """
    print_log("🔹", "STEP", "calculate_sheet_dimensions", "Starting dimension calculation")
    try:
        total_width = sum(col_widths) + 20
        total_height = (len(df) + 2) * 8 + 30
        
        total_width = max(total_width, 100)
        total_height = max(total_height, 100)
        
        print_log("✅", "SUCCESS", "calculate_sheet_dimensions", f"Completed: width={total_width}, height={total_height}")
        return total_width, total_height
    except Exception as e:
        print_log("🔴", "ERROR", "calculate_sheet_dimensions", f"Failed to calculate dimensions: {e}. Fix by checking width array.")
        raise

def write_sheet_to_pdf(pdf, file_name, sheet_name, df, font_name):
    """
    Writes a single DataFrame sheet to the PDF instance.
    
    Args:
        pdf (FPDF): The PDF instance.
        file_name (str): The name of the source file.
        sheet_name (str): The name of the sheet being written.
        df (pd.DataFrame): The DataFrame contents.
        font_name (str): The font family to use.
    """
    print_log("🔹", "STEP", "write_sheet_to_pdf", f"Starting write for sheet: {sheet_name}")
    try:
        clean_column_names(df)
        
        col_widths = get_col_widths(df)
        col_widths = [min(w, MAX_COLUMN_WIDTH) for w in col_widths] 
        
        total_width, total_height = calculate_sheet_dimensions(df, col_widths)
        
        pdf.add_page(format=(total_width, total_height))
        
        pdf.set_font(font_name, style="B", size=14)
        pdf.cell(0, 10, text=f"Planilha: {file_name} - Aba: {sheet_name}", new_x="LMARGIN", new_y="NEXT", align="L")
        pdf.ln(5)
        
        pdf.set_font(font_name, size=10)
        with pdf.table(col_widths=col_widths, text_align="LEFT", width=sum(col_widths)) as table:
            row = table.row()
            for col in df.columns:
                row.cell(str(col))
            
            for _, data_row in df.iterrows():
                row = table.row()
                for item in data_row:
                    val = "" if pd.isna(item) else str(item)
                    row.cell(val)
        
        print_log("✅", "SUCCESS", "write_sheet_to_pdf", f"Completed writing sheet {sheet_name}")
    except Exception as e:
        print_log("🔴", "ERROR", "write_sheet_to_pdf", f"Failed to write sheet {sheet_name}: {e}. Fix by checking DataFrame content and FPDF capabilities.")
        raise

def process_single_file(folder_path, file_name):
    """
    Processes a single Excel file and converts it to PDF.
    
    Args:
        folder_path (str): The path containing the file.
        file_name (str): The file to process.
        
    Returns:
        bool: True if processed successfully or skipped naturally, False on error.
    """
    print_log("🔹", "STEP", "process_single_file", "Starting")
    print_log("ℹ️", "LOG", "process_single_file", f"Processing: {file_name} with specific_parameters folder_path={folder_path}")
    
    file_path = os.path.join(folder_path, file_name)
    pdf_path = os.path.join(folder_path, os.path.splitext(file_name)[0] + ".pdf")
    
    if os.path.exists(pdf_path):
        print_log("ℹ️", "LOG", "process_single_file", f"Skipping {file_name} (PDF already exists)")
        print_log("✅", "SUCCESS", "process_single_file", f"Completed skipping {file_name}")
        return True
        
    try:
        sheets_dict = pd.read_excel(file_path, sheet_name=None)
        pdf = FPDF()
        font_name = setup_fonts(pdf)
        has_content = False
        
        for sheet_name, df in sheets_dict.items():
            if df.empty and df.columns.empty:
                print_log("ℹ️", "LOG", "process_single_file", f"Sheet '{sheet_name}' is empty. Ignoring.")
                continue
            
            has_content = True
            write_sheet_to_pdf(pdf, file_name, sheet_name, df, font_name)

        if has_content:
            pdf.output(pdf_path)
            print_log("✅", "SUCCESS", "process_single_file", f"Completed saving: {os.path.basename(pdf_path)}")
        else:
            print_log("ℹ️", "LOG", "process_single_file", f"File {file_name} didn't contain valid data in any sheet.")
            print_log("✅", "SUCCESS", "process_single_file", f"Completed processing empty file {file_name}")
            
        return True
    except Exception as e:
        print_log("🔴", "ERROR", "process_single_file", f"Failed to process {file_name}: {e}. Fix by validating file integrity and permissions.")
        return False

def export_to_pdf_pure_python(folder_path):
    """
    Main function to orchestrate the conversion of all Excel files in a folder to PDF.
    
    Args:
        folder_path (str): The folder containing the files to convert.
    """
    print_log("🔹", "STEP", "export_to_pdf_pure_python", f"Starting conversion cycle in {folder_path}")
    
    try:
        files = get_excel_files(folder_path)
    except Exception:
        files = []
    
    if not files:
        print_log("ℹ️", "LOG", "export_to_pdf_pure_python", "No spreadsheet files found.")
        print_log("✅", "SUCCESS", "export_to_pdf_pure_python", "Completed cycle with 0 files.")
        return
        
    successes = 0
    failures = 0
    total = len(files)

    for i, file_name in enumerate(files, 1):
        print_log("🔹", "STEP", "export_to_pdf_pure_python", f"Processing item {i} of {total}")
        result = process_single_file(folder_path, file_name)
        if result:
            successes += 1
        else:
            failures += 1

    # End of cycle: Summary with totals
    print_log("✅", "SUCCESS", "export_to_pdf_pure_python", f"Completed cycle. Successes: {successes}, Failures: {failures}")

    # Visual Summary Box
    box_width = 50
    inner_width = box_width - 2
    
    summary_box = (
        f"╔{'═' * inner_width}╗\n"
        f"║{'Processing Summary'.center(inner_width)}║\n"
        f"╠{'═' * inner_width}╣\n"
        f"║ {f'Total Processed: {total}'.ljust(inner_width - 2)} ║\n"
        f"║ {f'Successes:       {successes}'.ljust(inner_width - 2)} ║\n"
        f"║ {f'Failures:        {failures}'.ljust(inner_width - 2)} ║\n"
        f"╚{'═' * inner_width}╝"
    )
    print(summary_box)

if __name__ == "__main__":
    export_to_pdf_pure_python(os.getcwd())
