# Copyright (c) 2026 emuvi
# SPDX-License-Identifier: MIT

import os
import re
import sys
from typing import Optional, Tuple

def remove_time_from_filename(filename: str) -> Tuple[Optional[str], Optional[str]]:
    """
    Checks if the filename contains the specific time format added by the rename scripts
    and removes it, preserving prefixes and the rest of the filename.
    
    Args:
        filename (str): The current name of the file.
        
    Returns:
        tuple: (new_name, skip_reason). The newly generated filename, or None if no change is needed/possible.
    """
    # Matches the exact time format generated by the scripts: YYYY.MM.DD_HH.MM.SS
    time_regex = r"\d{4}\.\d{2}\.\d{2}_\d{2}\.\d{2}\.\d{2}"
    
    # Check for: [ Prefix ] - Time - Rest
    pattern_prefix = f"^(\\[ .*? \\] - ){time_regex}(?: - |- | )?(.*)$"
    match = re.match(pattern_prefix, filename)
    if match:
        prefix_part = match.group(1)
        rest_part = match.group(2)
        if not rest_part:
            return None, "Removing time would leave file without name/extension"
        return f"{prefix_part}{rest_part}", None
        
    # Check for: Time - Rest
    pattern_no_prefix = f"^{time_regex}(?: - |- | )?(.*)$"
    match = re.match(pattern_no_prefix, filename)
    if match:
        rest_part = match.group(1)
        if not rest_part:
            return None, "Removing time would leave file without name/extension"
        return rest_part, None
        
    return None, "No matching time format found in filename"

def get_safe_target_path(directory: str, filename: str) -> str:
    """
    Generates a unique file path within the given directory to avoid overwriting.
    """
    target_path = os.path.join(directory, filename)
    name_part, ext = os.path.splitext(filename)
    counter = 1
    
    while os.path.exists(target_path):
        new_name = f"{name_part} ({counter}){ext}"
        target_path = os.path.join(directory, new_name)
        counter += 1
        
    return target_path

def rename_file(filepath: str, directory: str, filename: str) -> bool:
    """
    Handles the operation to remove time from a single file's name.
    """
    try:
        new_name, skip_reason = remove_time_from_filename(filename)
        if not new_name:
            print(f"[*] Skipping file...")
            print(f"    File: '{filename}'")
            print(f"    Reason: {skip_reason}\n")
            return True

        new_filepath = get_safe_target_path(directory, new_name)
        final_name = os.path.basename(new_filepath)
        
        print(f"[*] Renaming file...")
        print(f"    From: '{filename}'")
        print(f"    To:   '{final_name}'")
        
        os.rename(filepath, new_filepath)
        print(f"[+] Successfully renamed '{filename}'.\n")
        return True
        
    except PermissionError as e:
        print(f"[-] Permission Denied renaming '{filename}': {e}\n")
    except OSError as e:
        print(f"[-] OS Error renaming '{filename}': {e}\n")
    except Exception as e:
        print(f"[-] Unexpected error renaming '{filename}': {e}\n")
        
    return False

def filter_eligible_files(directory: str) -> list:
    """
    Scans the directory for files that are eligible for renaming.
    """
    print(f"[*] Scanning directory '{directory}' for files to rename...")
    eligible_files = []
    
    try:
        files = os.listdir(directory)
    except PermissionError as e:
        print(f"[-] Permission Denied accessing directory '{directory}': {e}")
        return []
    except Exception as e:
        print(f"[-] Unexpected error accessing directory '{directory}': {e}")
        return []

    for filename in files:
        filepath = os.path.join(directory, filename)
        
        if not os.path.isfile(filepath):
            continue
            
        # Ignore system/script files or .py/.url files
        if filename.startswith('!-') or filename == os.path.basename(__file__) or filename.lower().endswith(('.py', '.url')):
            continue
            
        eligible_files.append(filename)
        
    print(f"[+] Found {len(eligible_files)} eligible file(s) for renaming evaluation.\n")
    return eligible_files

def main():
    """
    Main execution function. Orchestrates the filtering and renaming
    of files within the script's directory to remove time formats.
    """
    print("=" * 50)
    print("   Noterun Remove-Time Rename Script Initialized")
    print("=" * 50)
    
    script_dir = os.path.dirname(os.path.abspath(__file__))
    files_to_process = filter_eligible_files(script_dir)
    
    if not files_to_process:
        print("[*] No files to process. Exiting.")
        return 0
        
    print("-" * 50)
    
    success_count = 0
    failure_count = 0
    
    for filename in files_to_process:
        filepath = os.path.join(script_dir, filename)
        if rename_file(filepath, script_dir, filename):
            success_count += 1
        else:
            failure_count += 1
            
    print("-" * 50)
    print(f"[*] Renaming process completed.")
    print(f"[+] Processed successfully: {success_count}")
    
    if failure_count > 0:
        print(f"[-] Errors encountered: {failure_count}")
        return 1
    else:
        print("[+] All files processed without errors!")
        return 0

if __name__ == '__main__':
    exit_code = main()
    input("\nPress Enter to exit...")
    sys.exit(exit_code)