# Copyright (c) 2026 emuvi
# SPDX-License-Identifier: MIT

import os
import re
import sys
import time
from typing import Optional, Tuple, List

def get_current_time() -> str:
    """
    Returns the current local time formatted as [HH:MM:SS].
    
    Returns:
        str: The formatted timestamp.
    """
    return time.strftime("[%H:%M:%S]")

def remove_prefix_from_filename(filename: str) -> Tuple[Optional[str], Optional[str]]:
    """
    Checks if the filename contains the prefix format added by the rename scripts
    and removes it, preserving the rest of the filename (e.g. index, time, original name).
    
    Args:
        filename (str): The current name of the file.
        
    Returns:
        tuple: (new_name, skip_reason). The newly generated filename, or None if no change is needed/possible.
    """
    # Matches the exact prefix format generated by the scripts: [ Prefix ] - 
    pattern_prefix = r"^\[ .*? \] - (.*)$"
    match = re.match(pattern_prefix, filename)
    if match:
        rest_part = match.group(1)
        if not rest_part:
            return None, "Removing prefix would leave file without name/extension"
        return rest_part, None
        
    return None, "No matching prefix format found in filename"

def get_safe_target_path(directory: str, filename: str) -> str:
    """
    Generates a unique file path within the given directory to avoid overwriting.
    
    Args:
        directory (str): The destination directory path.
        filename (str): The desired filename.
        
    Returns:
        str: A safe, unique file path.
    """
    target_path = os.path.join(directory, filename)
    name_part, ext = os.path.splitext(filename)
    counter = 1
    
    while os.path.exists(target_path):
        new_name = f"{name_part} ({counter}){ext}"
        target_path = os.path.join(directory, new_name)
        counter += 1
        
    return target_path

def rename_file(filepath: str, directory: str, filename: str) -> bool:
    """
    Handles the operation to remove prefix from a single file's name.
    
    Args:
        filepath (str): The full path to the current file.
        directory (str): The directory containing the file.
        filename (str): The current name of the file.
        
    Returns:
        bool: True if operation was successful or file was cleanly skipped, False on error.
    """
    print(f"{get_current_time()} 🔹 [STEP] [rename_file] Starting - filepath: '{filepath}'")
    try:
        new_name, skip_reason = remove_prefix_from_filename(filename)
        if not new_name:
            print(f"{get_current_time()} ℹ️ [LOG] Skipping file '{filename}' - Reason: {skip_reason}")
            print(f"{get_current_time()} ✅ [SUCCESS] [rename_file] Completed gracefully without changes")
            return True

        new_filepath = get_safe_target_path(directory, new_name)
        final_name = os.path.basename(new_filepath)
        
        print(f"{get_current_time()} ℹ️ [LOG] Renaming file from '{filename}' to '{final_name}'")
        
        os.rename(filepath, new_filepath)
        print(f"{get_current_time()} ✅ [SUCCESS] [rename_file] Successfully renamed '{filename}' to '{final_name}'")
        return True
        
    except PermissionError as e:
        print(f"{get_current_time()} 🔴 [ERROR] [rename_file] Permission Denied renaming '{filename}': {e}. Fix: Check if the file is open in another program and ensure you have write permissions.")
    except OSError as e:
        print(f"{get_current_time()} 🔴 [ERROR] [rename_file] OS Error renaming '{filename}': {e}. Fix: Verify path validity and disk space.")
    except Exception as e:
        print(f"{get_current_time()} 🔴 [ERROR] [rename_file] Unexpected error renaming '{filename}': {e}. Fix: Check logs for further details.")
        
    return False

def filter_eligible_files(base_directory: str) -> List[Tuple[str, str, str]]:
    """
    Scans the directory and subdirectories for files that are eligible for renaming.
    
    Args:
        base_directory (str): The root directory path to scan.
        
    Returns:
        List[Tuple[str, str, str]]: A list of tuples (filepath, root, filename) for eligible files.
    """
    print(f"{get_current_time()} 🔹 [STEP] [filter_eligible_files] Starting - base_directory: '{base_directory}'")
    eligible_files = []
    
    for root, dirs, files in os.walk(base_directory):
        for filename in files:
            filepath = os.path.join(root, filename)
            
            # Ignore system/script files or .py/.url/.lnk files
            if filename.startswith('!-') or filename.lower().endswith(('.py', '.url', '.lnk')):
                continue
                
            eligible_files.append((filepath, root, filename))
        
    print(f"{get_current_time()} ✅ [SUCCESS] [filter_eligible_files] Found {len(eligible_files)} eligible file(s) for renaming evaluation")
    return eligible_files

def print_summary_box(total: int, successes: int, failures: int) -> None:
    """
    Prints a visual summary box with Unicode drawing characters showing the final results.
    
    Args:
        total (int): Total number of files processed.
        successes (int): Total number of successfully renamed files.
        failures (int): Total number of failures during renaming.
    """
    print(f"\n{get_current_time()} 🔹 [STEP] [print_summary_box] Starting summary display")
    print("╔═══════════════════════════════════════════════╗")
    print("║          Processing Summary                   ║")
    print("╠═══════════════════════════════════════════════╣")
    print(f"║ Total Processed: {total:<29}║")
    print(f"║ Successes:       {successes:<29}║")
    print(f"║ Failures:        {failures:<29}║")
    print("╚═══════════════════════════════════════════════╝")
    print(f"{get_current_time()} ✅ [SUCCESS] [print_summary_box] Summary display completed\n")

def main() -> int:
    """
    Main execution function. Orchestrates the filtering and renaming
    of files within the script's directory and subfolders to remove prefix formats.
    
    Returns:
        int: Exit code (0 for success, 1 for errors).
    """
    print("=" * 50)
    print(f"{get_current_time()} 🔹 [STEP] [main] Noterun Remove-Prefix (Subfolders) Rename Script Initialized")
    print("=" * 50)
    
    script_dir = os.path.dirname(os.path.abspath(__file__))
    files_to_process = filter_eligible_files(script_dir)
    
    if not files_to_process:
        print(f"{get_current_time()} ℹ️ [LOG] No eligible files to process. Exiting.")
        return 0
        
    print("-" * 50)
    
    success_count = 0
    failure_count = 0
    total_files = len(files_to_process)
    
    for i, (filepath, directory, filename) in enumerate(files_to_process, 1):
        print(f"{get_current_time()} 🔹 [STEP] [rename_cycle] Processing item {i} of {total_files}")
        print(f"{get_current_time()} ℹ️ [LOG] Processing: '{filename}' in directory '{directory}'")
        if rename_file(filepath, directory, filename):
            success_count += 1
        else:
            failure_count += 1
            
    print("-" * 50)
    print(f"{get_current_time()} ✅ [SUCCESS] [main] Renaming process completed")
    
    print_summary_box(total_files, success_count, failure_count)
    
    if failure_count > 0:
        print(f"{get_current_time()} 🔴 [ERROR] [main] Completed with {failure_count} errors")
        return 1
    else:
        print(f"{get_current_time()} ✅ [SUCCESS] [main] All files processed without errors!")
        return 0

if __name__ == '__main__':
    exit_code = main()
    input("\nPress Enter to exit...")
    sys.exit(exit_code)
